### ISSUE TITLE
Typo in Downloadable/Mode/Product

### ISSUE THREAD

**Issue by Swahjak** [SchumacherFM/Magento2-Mocks#2]
The folder `vendor/schumacherfm/mage2-mocks/Mocks/Downloadble/Mode/Product` should be `vendor/schumacherfm/mage2-mocks/Mocks/Downloadble/Model/Product` Notice the `Mode` vs `Model`

**Comment by Swahjak** [comment]
Haha, that's pretty fast man.

**Comment by SchumacherFM** [comment]
Thank you for reporting!
