### ISSUE TITLE
Latest release isn't matching composer.json

### ISSUE THREAD

**Issue by Tjitse-E** [SchumacherFM/Magento2-Mocks#4]
The latest release is in the composer.json is [0.0.3](https://github.com/SchumacherFM/Magento2-Mocks/blob/master/composer.json#L8), but version 0.0.4 is already a [github release](https://github.com/SchumacherFM/Magento2-Mocks/releases/tag/0.0.4)

**Comment by SchumacherFM** [comment]
Sorry. I've fixed it with version 0.0.5
